<?php
namespace OC\PlatformBundle\Repository;

use OC\PlatformBundle\Entity\Advert;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{


    public function getAdvertWithCategories(array $categoryNames){
        $qb = $this->createQueryBuilder('advert');
        
        $qb ->leftJoin('advert.categories','categories')
            ->addSelect('categories')
        ;
        
        $qb->where($qb->expr()->in('categories.name',$categoryNames));
        
        return $qb->getQuery()->getResult();
    }
    
    /**
     * @return Advert[]
     */
    public function myFindAll(){
        $qb = $this->createQueryBuilder('a');
//        $qb->leftJoin('a.image','image')
//            ->addSelect('image')
//        ;
        return $qb->getQuery()->getResult();
    }

    /**
     * @param $id
     * @return null|Advert
     */
    public function findOneById($id){
        $qb = $this->createQueryBuilder('advert');
        
        $qb ->where('advert.id=:id')
            ->setParameter('id',$id)
            ;
        
        return $qb->getQuery()->getOneOrNullResult();
    }
    
    
    
}
